### ISSUE TITLE
Throttle support for Addic7ed temporary ip ban 

### ISSUE THREAD

**Issue by PotatoQuality** [morpheus65535/bazarr#1034]
**Describe the bug**
Addic7ed does temporary ip bans after a while when you trying to download subs from the website with bazarr.
Its look like that bazarr doesn't detect it and keeps retrying Addic7ed. As a result, it will slow down the subtitle search.

**To Reproduce**
1. Enable Addic7ed as a provider
2. execute searching subs
3. wait
4. see errors in the logs

**Expected behavior**
Considering a throttle for Addic7ed around 1 hour for preventing searching on a website where you got ip blocked ;)
(Or maybe a rate limit for searching on the Addic7ed maybe 3 minutes between searches?)

**Screenshots**
![image](https://user-images.githubusercontent.com/2944704/88596444-600d9a80-d065-11ea-99b6-f8dca5b971fa.png)

**Software (please complete the following information):**
- Bazarr Version: 0.9
- Sonarr Version: 3.0.3.904
- Radarr Version: 0.2.0.1504
- Operating System: Linux-4.19.107-Unraid-x86_64-with
- Python Version: 3.8.5

**Additional context**

**Comment by morpheus65535** [comment]
Can you confirm if the fix I've just pushed resolve this issue? Thanks!

**Comment by PotatoQuality** [comment]
Thanks -again- for your quick fix, i don't see any different yet (still spam in the log), but maybe the linuxeserver docker building is slow at the moment?

**Comment by morpheus65535** [comment]
If I remember correctly, they are checking once every 2 hours for changes. Wait for a couple of hours and test again.

**Comment by PotatoQuality** [comment]
Hi morpheus, i checked again. No new updates cna be pulled from linuxserver.
So I assume I'm on the last development version?

Im seeing still the same behaver

![image](https://user-images.githubusercontent.com/2944704/88839132-e5668b80-d1da-11ea-8914-28f5b45660f1.png)

The weird part is that is already throttled for 1 hour, but Bazarr is still shooting calls too Addic7ed.

![image](https://user-images.githubusercontent.com/2944704/88839291-28c0fa00-d1db-11ea-8961-050001bf496a.png)

![image](https://user-images.githubusercontent.com/2944704/88839488-6de52c00-d1db-11ea-8b10-bd5d40077b99.png)

**Comment by PotatoQuality** [comment]
Some more logs

[bazarr (3).log](https://github.com/morpheus65535/bazarr/files/4996797/bazarr.3.log)

**Comment by morpheus65535** [comment]
Just to be sure you are using `linuxserver/bazarr:development`, tight?

**Comment by PotatoQuality** [comment]
Yes!
![image](https://user-images.githubusercontent.com/2944704/88961339-2e831200-d2a5-11ea-87cc-7973282d29a4.png)

**Comment by morpheus65535** [comment]
@pannal this is the one I was talking about. Thanks!

**Comment by morpheus65535** [comment]
This latest commit should fix the issue, thanks to @pannal for it. @PotatoQuality can you confirm?

**Comment by PotatoQuality** [comment]
Thanks for the fix @pannal and @morpheus65535. Waiting for the new build from LS.

**Comment by PotatoQuality** [comment]
I checked, it looks a little better, but 10 minutes is a little bit short. can we change that for at least 1 hour? 

![image](https://user-images.githubusercontent.com/2944704/89811611-3497af00-db3f-11ea-924c-a163ff459928.png)

**Comment by morpheus65535** [comment]
Strangely I'm getting the same 10 minutes throttling when it should be 20 minutes. Should it be longer? Maybe...

@pannal any thought about this?

**Comment by morpheus65535** [comment]
Should be fixed now: 60 minutes. Can you confirm?

**Comment by morpheus65535** [comment]
I've made another commit to dev branch. Can you test it please?

**Comment by PotatoQuality** [comment]
Hi @morpheus65535 last change fixed the problem on my end! Thanks for both @pannal and @morpheus65535  for fixing the problem!!!

`Throttling addic7ed for 1 hour, until 20/08/18 15:43, because of: ConnectTimeout. Exception info: MaxRetryError("HTTPSConnectionPool(host='www.addic7ed.com', port=443): Max retries exceeded with url: /login.php (Caused by ConnectTimeoutError(, 'Connection to www.addic7ed.com timed out. (connect timeout=10)'))")`

**Comment by morpheus65535** [comment]
Good news! Thanks for the feedback!
