### ISSUE TITLE
Minor: text overflow in manual search

### ISSUE THREAD

**Issue by ngosang** [morpheus65535/bazarr#1336]
**Describe the bug**
I don't want to scroll to the right with each search :)

**Screenshots**
![image](https://user-images.githubusercontent.com/10577978/112554240-352b4000-8dc6-11eb-8b48-22c173f94665.png)

**Software (please complete the following information):**
 - Bazarr: development branch

**Comment by morpheus65535** [comment]
Should be fixed in upcoming v0.9.4-beta.9. Can you test it and confirm please?

**Comment by ngosang** [comment]
It's not fixed

**Comment by morpheus65535** [comment]
It's not yet released: `upcoming` :-P

**Comment by ngosang** [comment]
Ok, tested again.
It's better but I still see the scroll. I can't click in the arrow to see the full text.

![image](https://user-images.githubusercontent.com/10577978/112749743-b2240880-8fc4-11eb-91e4-2077c6d89237.png)

**Comment by morpheus65535** [comment]
The release column can't use more than 30% of the viewport width. What kind of resolution you're using?

**Comment by ngosang** [comment]
2560x1440

**Comment by morpheus65535** [comment]
ok I'll change it percent of the modal instead of the viewport.  It will make more sense on large resolution monitor.

**Comment by morpheus65535** [comment]
Should be fixed in next nightly.
