### ISSUE TITLE
Bazarr becomes unresponsive when running sync tasks

### ISSUE THREAD

**Issue by ADRFranklin** [morpheus65535/bazarr#1609]
**Describe the bug**
After restarting Bazarr the sync task will generally start running and try syncing all the sonarr and radarr data across, however towards the end of the scan the backend will become unresponsive and the web ui fails to connect. This also means the task never finishes, so on each restart the task will run again (I assume), which causes the same issue.

**To Reproduce**
Start bazarr and wait for syncing task to run

**Expected behavior**
I expect the sync task to complete successfully

**Screenshots**
https://i.imgur.com/EQakLcU.png

**Software (please complete the following information):**
 - Bazarr: v1.0.0
 - Radarr version: 4.0.0.5450
 - Sonarr version: 3.0.6.1373
 - OS: Ubuntu 20.04, Docker, Hotio Image
 
 (useful but unrelated data)
- Browser: Brave, V1.31.88
- Reverse Proxy: Traefik v2.3.7

**Additional context**
After going through the debug logs and only seeing requests being made, this is the only line that differed and was also the last line printed out before the app went unresponsive.

```
2021-11-09 05:32:34,088 - peewee (7fc57cc8e260) :  DEBUG (peewee:3132) - ('SELECT "t1"."sonarrSeriesId", "t1"."sonarrEpisodeId", "t1"."title", "t1"."path", "t1"."season", "t1"."episode", "t1"."scene_name", "t1"."monitored", "t1"."format", "t1"."resolution", "t1"."video_codec", "t1"."audio_codec", "t1"."episode_file_id", "t1"."audio_language", "t1"."file_size" FROM "table_episodes" AS "t1"', [])
```

This problem has only just started being a problem, I have no noticed it in the past and I am unaware of when it actually started happening as I am very busy and don't use usually need to look at Bazarr.

**Comment by morpheus65535** [comment]
It's a long lasting issue that should be fixed in 1.0.1-beta.1. You can try it and confirm please?

BTW, you'll probably run into issue with Brave. I suggest you stick to Chrome or Firefox.

**Comment by ADRFranklin** [comment]
All I can say for now about the beta is that when I start Bazarr, the sync task no longer runs on start. I seem to be unable to click the refresh icon to start the task too, since when I try, nothing happens at all. So I'm not sure if the task has just been disabled entirely or not?

**Comment by morpheus65535** [comment]
No, the task haven't been disabled at all. It's just not blocking the UI thread anymore.

**Comment by ADRFranklin** [comment]
The webinterface is no longer showing running tasks then or I am unable to run them myself regardless. It doesn't look like anything has been updated since, one of my shows still shows as having no episodes. So I'm unsure as to what is happening anymore.

**Comment by morpheus65535** [comment]
Did I said "do not use Brave"? It's blocking most JavaScript.

**Comment by ADRFranklin** [comment]
I'm actually using firefox right now for it, and nothing is happening, the same happens on brave too tbh.

**Comment by morpheus65535** [comment]
Come back to Discord, we'll chat there. Getting back in 20 minutes.
