### ISSUE TITLE
BAZARR cannot parse JSON

### ISSUE THREAD

**Issue by evripidesk** [morpheus65535/bazarr#1623]
Hello

last days i get the below error and bazarr is always synch episodes from sonarr

BAZARR cannot parse JSON returned by SignalR feed. This is caused by a permissions issue when Sonarr try to access its /config/.config directory. You should fix permissions on that directory and restart Sonarr. Also, if you're a Docker image user, you should make sure you properly defined PUID/PGID environment variables. Otherwise, please contact Sonarr support.

**Comment by bakerboy448** [comment]
This is not a Bazarr issue nor a bug.

Did you fix your permissions and ownership as the error says?

**Comment by joelkay** [comment]
I've got a similar issue to this, I tried setting files to 664 and dirs to 775 also made sure both containers use the same uid and gid:
![image](https://user-images.githubusercontent.com/4349824/144536801-62cb46fa-b14d-4c43-9d57-f4431821daea.png)

still getting this error, any ideas on what else I can try?

**Comment by morpheus65535** [comment]
> still getting this error, any ideas on what else I can try?

`Otherwise, please contact Sonarr support.`

**Comment by uliaraujo** [comment]
Hi, I have the same problem with the version 1.0.1 and 1.0.2 too. Until the version 1.0.0 everything is fine. I run Sonarr and Bazarr in docker container. I try set permission on /config sonarr folder, but not successfully.

**Comment by bakerboy448** [comment]
How does one unsuccessfully set permissions?

Either sonarr doesn't have access or you've configured it to be too permissive and too open.

**Comment by uliaraujo** [comment]
Ok... I solved the problem doing a fresh install of Sonarr. (Remember to do a backup in Sonarr interface to restore later)
Maybe is a bug in file permission of docker container. Bazarr 1.0.2 running with no error now. Thanks

**Comment by mduijm** [comment]
Hi,

running into the same issue. Tried the above mentioned approach to re-install, but no luck.. 

Bazarr Version:1.0.3-beta.30
Package Version: v1.0.3-beta.30-ls281 by [linuxserver.io](https://linuxserver.io)
Sonarr Version: 3.0.6.1470
Radarr Version: 4.0.4.5922
Operating System: Linux-5.10.0-11-amd64-x86_64-with
Python Version: 3.9.5
Bazarr Directory: /app/bazarr/bin
Bazarr Config Directory: /config
Uptime 0d 00:03:24

*****       | 2022-02-22 09:06:51,313 - root                             (7fd176099b38) :  ERROR (signalr_client:48) - BAZARR cannot parse JSON returned by SignalR feed. This is caused by a permissions issue when Sonarr try to access its /config/.config directory.Typically permissions are too permissive - only the user and group Sonarr runs as should have Read/Write permissions (e.g. files 664 / folders 775)You should fix permissions on that directory and restart Sonarr. Also, if you're a Docker image user, you should make sure you properly defined PUID/PGID environment variables. Otherwise, please contact Sonarr support.

Below is folder of the sonarr deployment, the blurred part is my user account, which has UID/GID 1000 and in my docker-compose I also mention the 1000 for both rights. 

<img width="667" alt="2022-02-22_09-58-52" src="https://user-images.githubusercontent.com/79192366/155097882-f955a9ad-c47b-4426-97fb-6ad7e82687a0.png">

**Comment by mduijm** [comment]
fixed... problem is due to usage op RP (Swag)

**Comment by morpheus65535** [comment]
> fixed... problem is due to usage op RP (Swag)

Never make *arr talk through a reverse proxy. Always do direct connection.

**Comment by guiramos** [comment]
> fixed... problem is due to usage op RP (Swag)

Can you explain more?

**Comment by morpheus65535** [comment]
> 

He was connecting Bazarr to Sonarr and Radarr through a reverse proxy (SWAG from LSIO) when he shouldn't have. This is not recommanded because it could cause multiple issues. You must connect directly to Sonarr and Radarr.

**Comment by guiramos** [comment]
Ok. Yeah, I am connecting directly and this problem is still happening.

Hasnt happening in my previous server. I had to restore a backup, where all my docker container volumes were(including bazarr, sonarr, and radarr), and now this is happening.

**Comment by morpheus65535** [comment]
@guiramos I'm pretty sure it's a different issue. Open your own issue with the full exception stack or come see us on Discord for live support.
