### ISSUE TITLE
Postgres will always return error once an error is given, until restart

### ISSUE THREAD

**Issue by jdeppa** [morpheus65535/bazarr#2071]
**Describe the bug**
Once there is an error with the postgres db (for example constraint violation), any transaction to postgres will be ignored.

**To Reproduce**
1. Have a constraint violation
2. Wait for next db transaction from bazarr (for example update list from radarr or sonarr)
3. Check logs

**Expected behavior**
One error should not cause subsequent postgres transactions to not go through

**Logs**
postgres container:
```
2023-02-24 08:30:24.201 UTC [63687] ERROR:  duplicate key value violates unique constraint "tablemovies_path"
2023-02-24 08:30:24.201 UTC [63687] DETAIL:  Key (path)=(/data/m/movies/Alone (2020)/Alone (2020) - Remux-1080p Proper AVC DTS-HD MA.mkv) already exists.
2023-02-24 08:30:24.201 UTC [63687] STATEMENT:  UPDATE "table_movies" SET --details removed--
2023-02-24 08:30:24.347 UTC [63687] ERROR:  current transaction is aborted, commands ignored until end of transaction block
2023-02-24 08:30:24.347 UTC [63687] STATEMENT:  UPDATE "table_movies" SET --details removed--
2023-02-24 08:36:06.994 UTC [63687] ERROR:  current transaction is aborted, commands ignored until end of transaction block
...
2023-02-25 04:33:50.882 UTC [63675] STATEMENT:  SELECT "t1"."sonarrEpisodeId", "t1"."path", "t1"."sonarrSeriesId" FROM "table_episodes" AS "t1"
2023-02-25 04:34:05.339 UTC [63687] ERROR:  current transaction is aborted, commands ignored until end of transaction block
2023-02-25 04:34:05.339 UTC [63687] STATEMENT:  SELECT "t1"."path" FROM "table_shows" AS "t1"
2023-02-25 04:35:59.282 UTC [63707] ERROR:  current transaction is aborted, commands ignored until end of transaction block
2023-02-25 04:35:59.282 UTC [63707] STATEMENT:  SELECT "t1"."path" FROM "table_movies" AS "t1"
2023-02-25 04:48:51.090 UTC [63674] ERROR:  current transaction is aborted, commands ignored until end of transaction block
2023-02-25 04:48:51.090 UTC [63674] STATEMENT:  SELECT "t1"."sonarrEpisodeId", "t1"."path", "t1"."sonarrSeriesId" FROM "table_episodes" AS "t1"
2023-02-25 04:49:05.134 UTC [63675] ERROR:  current transaction is aborted, commands ignored until end of transaction block
2023-02-25 04:49:05.134 UTC [63675] STATEMENT:  SELECT "t1"."path" FROM "table_shows" AS "t1"
2023-02-25 04:50:58.706 UTC [63687] ERROR:  current transaction is aborted, commands ignored until end of transaction block
2023-02-25 04:50:58.706 UTC [63687] STATEMENT:  SELECT "t1"."path" FROM "table_movies" AS "t1"
2023-02-25 05:03:50.954 UTC [63674] ERROR:  current transaction is aborted, commands ignored until end of transaction block
2023-02-25 05:03:50.954 UTC [63674] STATEMENT:  SELECT "t1"."sonarrEpisodeId", "t1"."path", "t1"."sonarrSeriesId" FROM "table_episodes" AS "t1"
2023-02-25 05:04:04.250 UTC [63675] ERROR:  current transaction is aborted, commands ignored until end of transaction block
2023-02-25 05:04:04.250 UTC [63675] STATEMENT:  SELECT "t1"."path" FROM "table_shows" AS "t1"
2023-02-25 05:05:58.360 UTC [63687] ERROR:  current transaction is aborted, commands ignored until end of transaction block
2023-02-25 05:05:58.360 UTC [63687] STATEMENT:  SELECT "t1"."path" FROM "table_movies" AS "t1"
2023-02-25 05:18:50.729 UTC [63707] ERROR:  current transaction is aborted, commands ignored until end of transaction block
2023-02-25 05:18:50.729 UTC [63707] STATEMENT:  SELECT "t1"."sonarrEpisodeId", "t1"."path", "t1"."sonarrSeriesId" FROM "table_episodes" AS "t1"
2023-02-25 05:19:04.162 UTC [63674] ERROR:  current transaction is aborted, commands ignored until end of transaction block
and it keeps repeating
```
bazarr container:
```
2023-02-25 22:31:12,262 - root                             (7fc75c77eb38) :  ERROR (movies:139) - BAZARR cannot update movie /data/m/movies/Alone (2020)/Alone (2020) - Remux-1080p Proper AVC DTS-HD MA.mkv because of duplicate key value violates unique constraint "tablemovies_path"
DETAIL:  Key (path)=(/data/m/movies/Alone (2020)/Alone (2020) - Remux-1080p Proper AVC DTS-HD MA.mkv) already exists.

2023-02-25 22:31:12,279 - apscheduler.executors.default    (7fc75c77eb38) :  ERROR (base:131) - Job "update_movies (trigger: date[2023-02-25 22:29:05 CET], next run at: 2023-02-25 22:29:05 CET)" raised an exception

```

**Software (please complete the following information):**
 - Bazarr: 1.1.5-beta.24
 - OS: Ubuntu with Docker, linuxserver's image

**Additional context:**
Any reason autocommit is not used? I think it might avoid this issue. From what I know radarr is using autocommit, but bazarr is not. But I might be wrong, as I'm very well versed in postgres.

**Comment by halali** [comment]
Can you post full debug log?

**Comment by halali** [comment]
Im not fun of autocommit...

There need to be identified why it try to save duplicated path and handle it properly.

**Comment by jdeppa** [comment]
I have been trying to replicate the issue with clean containers, but for some reason, I'm not able to.

The underlying problem for my specific case is that, for some reason, radarr has allowed the same path to be used for two different movies. In this example, `/data/m/movies/Alone (2020)` is the path to two movies of the same name and the same year, tmdb id 509635 and tmdb id 664425. In the path `/data/m/movies/Alone (2020)` there is only one file, that is `Alone (2020) - Remux-1080p Proper AVC DTS-HD MA.mkv`, and in radarr, both movies are listed as downloaded, both pointing to this same file.

After I fix this in radarr (change the folder name for the movies to something unique), there's no problem with bazarr anymore.

But the reason I opened this issue isn't because of this particular case, but because I think bazarr should be able to recover from postgres db error if an error should occur, regardless if the error is the same as mine or not.

Currently, the way bazarr behave (from what I can tell with my limited knowledge) is that if a statement comes to an error, it will still use the same connection to postgres to issue subsequent statements, but because there was an error with one statement previously, postgres will ignore all subsequent statements coming from the same connection, even though the subsequent statements will not give an error.

Again, I might be wrong with my deduction above, so correct me if I'm wrong. 

Below is the log from postgres container and full debug log from bazarr:
[bazarr log part1](http://sprunge.us/zM9T65)
[bazarr log part2](http://sprunge.us/P4QsOs)
[bazarr log part3](http://sprunge.us/uRocwx)
[bazarr log part4](http://sprunge.us/JA9NK8)
[bazarr log part5](http://sprunge.us/mqsXIl)
[postgres log](http://sprunge.us/IXqhw2)

**Comment by jdeppa** [comment]
From the logs above:

First error at timestamp: `2023-02-26 11:41:35,930` (bazarr log part2), problem is the problem I describe above.

Then at `2023-02-26 11:49:03,654` (bazarr log part3) and `2023-02-26 11:51:17,988` (bazarr log part4), bazarr has problem updating series from sonarr because postgres server is not accepting the statement due to previous error.

**Comment by halali** [comment]
fixed in upcoming beta

let me know if that helps

**Comment by morpheus65535** [comment]
@jdeppa can you provide feedback ASAP please? I'm waiting on this fix to merge dev branch to master.

**Comment by jdeppa** [comment]
I will try the new image ASAP

**Comment by jdeppa** [comment]
Nope, still the same. Exception when syncing sonarr when only radarr's data has error. Do you need new debug logs?

**Comment by halali** [comment]
yes post it please... as now transaction should be thread safe

**Comment by jdeppa** [comment]
[bazarr log part1](http://sprunge.us/Tvp86Z)
[bazarr log part2](http://sprunge.us/oWYqlu)
[bazarr log part3](http://sprunge.us/widLec)
[bazarr log part4](http://sprunge.us/o2ci04)
[postgres log](http://sprunge.us/pXtWfb)

First error at timestamp `2023-02-28 18:16:51,602` (bazarr log part3)
Subsequent errors: 
- `2023-02-28 18:20:19,703` (bazarr log part4)
- `2023-02-28 18:27:21,629` (bazarr log part4)

**Comment by halali** [comment]
hopefully fixed now this one.

but you really need fix your duplicated path

**Comment by jdeppa** [comment]
Yes, the duplicated path has been fixed on my main instance. The logs are from running from snapshots that I have done before I fixed the duplicated path. 

I will try the new build once it's out.

**Comment by jdeppa** [comment]
Fixed in v1.1.5-beta.27

**Comment by morpheus65535** [comment]
Thanks for the feedback! :-)
