### ISSUE TITLE
Bazarr does not reconnect to Postgres after Postgres is restarted

### ISSUE THREAD

**Issue by onedr0p** [morpheus65535/bazarr#2161]
**Describe the bug**

Logs show this message for both sonarr and radarr

**To Reproduce**

Deployed with postgresql 14.8

**Expected behavior**

Bazarr to reconnect to postgres after postgres is restarted.

Current workaround is to restart bazarr after postgres has restarted.

**Screenshots**

**Software (please complete the following information):**
 - Bazarr: `1.2.1`
 - Radarr version `4.5.2.7388`
 - Sonarr version `4.0.0.534`
 - OS: `ghcr.io/onedr0p/bazarr:1.2.1` ([Dockerfile](https://github.com/onedr0p/containers/blob/main/apps/bazarr/Dockerfile))

**Additional context**

```
Traceback (most recent call last):
  File "/app/bazarr/../libs/peewee.py", line 3219, in execute_sql
    cursor = self.cursor(commit)
             ^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/../libs/peewee.py", line 3206, in cursor
    return self._state.conn.cursor()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.InterfaceError: connection already closed
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/bazarr/../libs/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/radarr/sync/movies.py", line 27, in update_movies
    check_radarr_rootfolder()
  File "/app/bazarr/radarr/rootfolder.py", line 59, in check_radarr_rootfolder
    get_radarr_rootfolder()
  File "/app/bazarr/radarr/rootfolder.py", line 36, in get_radarr_rootfolder
    radarr_movies_paths = list(TableMovies.select(TableMovies.path).dicts())
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/../libs/peewee.py", line 7038, in __iter__
    self.execute()
  File "/app/bazarr/../libs/peewee.py", line 1946, in inner
    return method(self, database, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/../libs/peewee.py", line 2017, in execute
    return self._execute(database)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/../libs/peewee.py", line 2190, in _execute
    cursor = database.execute(self)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/../libs/peewee.py", line 3234, in execute
    return self.execute_sql(sql, params, commit=commit)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/../libs/playhouse/shortcuts.py", line 254, in execute_sql
    raise exc
  File "/app/bazarr/../libs/playhouse/shortcuts.py", line 250, in execute_sql
    return super(ReconnectMixin, self).execute_sql(sql, params, commit)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/../libs/peewee.py", line 3218, in execute_sql
    with __exception_wrapper__:
  File "/app/bazarr/../libs/peewee.py", line 2994, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/app/bazarr/../libs/peewee.py", line 191, in reraise
    raise value.with_traceback(tb)
  File "/app/bazarr/../libs/peewee.py", line 3219, in execute_sql
    cursor = self.cursor(commit)
             ^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/../libs/peewee.py", line 3206, in cursor
    return self._state.conn.cursor()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
peewee.InterfaceError: connection already closed
```

**Comment by morpheus65535** [comment]
This issue won't be fixed in 1.2.2 but should be in 1.3.0 that will include a complete ORM replacement and better database connectivity to PostgreSQL. I'll close it but in the meantime you should just restart Bazarr when PostgreSQL reatart.

**Comment by buroa** [comment]
This is an unacceptable answer @morpheus65535.

**Comment by morpheus65535** [comment]
@buroa Still, it's my answer. You either go back to sqlite or wait for the upcoming 1.3.0 version.

**Comment by onedr0p** [comment]
Thanks for reopening, it should help other people discover issues with postgres or at least make it so they think twice about migrating to it. I wish I knew this was an issue before I did the migration, oh well.

**Comment by morpheus65535** [comment]
@onedr0p ok so I deployed a postgres14 container, migrated my Sqlite database to Postgres and make sure that my Bazarr instance is using the postgres database. Of course, when I stop the postgres docker container, connection drop and I get exception when refreshing browser. But, as soon as I restart the Postgres container and refresh my browser, everything go back to normal.

The log you provided show that the connection got lost during a scheduled task execution. Of course, if Bazarr lost connection to database during this task, the exception get raised and task don't complete successfully. If you start the task again and don't cut the cord to the database, the task will complete without any issue.

Just to be sure, isn't that what you would expect?

**Comment by onedr0p** [comment]
It doesn't appear to be related to postgres being restarted, because I am trying to run jobs now and I get the same error.

```
Traceback (most recent call last):
  File "/app/bazarr/../libs/peewee.py", line 3219, in execute_sql
    cursor = self.cursor(commit)
             ^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/../libs/peewee.py", line 3206, in cursor
    return self._state.conn.cursor()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.InterfaceError: connection already closed
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/bazarr/../libs/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/subtitles/upgrade.py", line 29, in upgrade_subtitles
    episodes_to_upgrade = get_upgradable_episode_subtitles()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/subtitles/upgrade.py", line 217, in get_upgradable_episode_subtitles
    if not upgradable_episodes:
  File "/app/bazarr/../libs/peewee.py", line 2047, in __len__
    self._ensure_execution()
  File "/app/bazarr/../libs/peewee.py", line 2029, in _ensure_execution
    self.execute()
  File "/app/bazarr/../libs/peewee.py", line 1946, in inner
    return method(self, database, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/../libs/peewee.py", line 2017, in execute
    return self._execute(database)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/../libs/peewee.py", line 2190, in _execute
    cursor = database.execute(self)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/../libs/peewee.py", line 3234, in execute
    return self.execute_sql(sql, params, commit=commit)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/../libs/playhouse/shortcuts.py", line 254, in execute_sql
    raise exc
  File "/app/bazarr/../libs/playhouse/shortcuts.py", line 250, in execute_sql
    return super(ReconnectMixin, self).execute_sql(sql, params, commit)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/../libs/peewee.py", line 3218, in execute_sql
    with __exception_wrapper__:
  File "/app/bazarr/../libs/peewee.py", line 2994, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/app/bazarr/../libs/peewee.py", line 191, in reraise
    raise value.with_traceback(tb)
  File "/app/bazarr/../libs/peewee.py", line 3219, in execute_sql
    cursor = self.cursor(commit)
             ^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/../libs/peewee.py", line 3206, in cursor
    return self._state.conn.cursor()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
peewee.InterfaceError: connection already closed
```

And I am also getting this error:

```
Traceback (most recent call last):
  File "/app/bazarr/subtitles/indexer/utils.py", line 80, in guess_external_subtitles
    text = text.decode(\'utf-8\')
           ^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: \'utf-8\' codec can\'t decode byte 0xba in position 3: invalid start byte
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/bazarr/subtitles/indexer/series.py", line 93, in store_subtitles
    subtitles = guess_external_subtitles(full_dest_folder_path, subtitles, "series",
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/subtitles/indexer/utils.py", line 90, in guess_external_subtitles
    detector = Detector()
               ^^^^^^^^^^
  File "/app/bazarr/../libs/charamel/detector.py", line 67, in __init__
    self._weights = load_weights(encodings)
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/../libs/charamel/resources/__init__.py", line 71, in load_weights
    weights[encoding] = _unpack(WEIGHT_DIRECTORY / f\'{encoding}.gzip\', pattern=\'>e\')
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/../libs/charamel/resources/__init__.py", line 29, in _unpack
    with gzip.open(file, \'rb\') as data:
         ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/gzip.py", line 58, in open
    binary_file = GzipFile(filename, gz_mode, compresslevel)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/gzip.py", line 174, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or \'rb\')
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: \'/app/bazarr/../libs/charamel/resources/weights/Encoding.ASCII.gzip\
```

**Comment by morpheus65535** [comment]
@onedr0p Python 3.11 is unsupported. We haven't run any test with it to see how it goes.

**Comment by onedr0p** [comment]
That appears to have fixed the postgres issue, I switched to build my container with 3.10 instead of 3.11.

https://github.com/onedr0p/containers/commit/5cd8f0148e25645d4943a84ee2c8605aaeeaeb47

Sorry for not trying to downgrade to 3.10 sooner.

However I am still seeing this error in my bazarr logs:

```
Traceback (most recent call last):
  File "/app/bazarr/subtitles/indexer/utils.py", line 80, in guess_external_subtitles
    text = text.decode(\'utf-8\')
           ^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: \'utf-8\' codec can\'t decode byte 0xf0 in position 35: invalid continuation byte
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/bazarr/subtitles/indexer/movies.py", line 94, in store_subtitles_movie
    subtitles = guess_external_subtitles(full_dest_folder_path, subtitles, "movie",
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/subtitles/indexer/utils.py", line 90, in guess_external_subtitles
    detector = Detector()
               ^^^^^^^^^^
  File "/app/bazarr/../libs/charamel/detector.py", line 67, in __init__
    self._weights = load_weights(encodings)
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/../libs/charamel/resources/__init__.py", line 71, in load_weights
    weights[encoding] = _unpack(WEIGHT_DIRECTORY / f\'{encoding}.gzip\', pattern=\'>e\')
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/../libs/charamel/resources/__init__.py", line 29, in _unpack
    with gzip.open(file, \'rb\') as data:
         ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/gzip.py", line 58, in open
    binary_file = GzipFile(filename, gz_mode, compresslevel)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/gzip.py", line 174, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or \'rb\')
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: \'/app/bazarr/../libs/charamel/resources/weights/Encoding.ASCII.gzip\
```

**Comment by onedr0p** [comment]
I am going to go ahead and close this issue, I tried reverting back to alpine 3.17 but ran into this error on start. At this point I think I'll just let the project mature a bit more before continuing to use it with Postgres.

```
❯ k logs bazarr-0 -f
Defaulted container "bazarr" out of: bazarr, subcleaner, 01-init-db (init)
Bazarr starting...
Traceback (most recent call last):
  File "/app/bazarr/main.py", line 22, in <module>
    from init import *  # noqa E402
  File "/app/bazarr/init.py", line 183, in <module>
    from app.announcements import get_announcements_to_file
  File "/app/bazarr/app/announcements.py", line 13, in <module>
    from app.get_providers import get_enabled_providers
  File "/app/bazarr/app/get_providers.py", line 23, in <module>
    from app.event_handler import event_stream
  File "/app/bazarr/app/event_handler.py", line 3, in <module>
    from .app import socketio
  File "/app/bazarr/app/app.py", line 8, in <module>
    from .database import database
  File "/app/bazarr/app/database.py", line 113, in <module>
    class TableEpisodes(BaseModel):
  File "/app/bazarr/../libs/peewee.py", line 6342, in __new__
    cls._meta.add_field(name, field)
  File "/app/bazarr/../libs/peewee.py", line 6126, in add_field
    field.bind(self.model, field_name, set_attribute)
  File "/app/bazarr/../libs/peewee.py", line 4878, in bind
    self._db_hook(model._meta.database)
  File "/app/bazarr/../libs/peewee.py", line 4870, in _db_hook
    self._constructor = database.get_binary_type()
  File "/app/bazarr/../libs/peewee.py", line 4017, in get_binary_type
    return psycopg2.Binary
AttributeError: 'NoneType' object has no attribute 'Binary'
Bazarr exited.
```

**Comment by morpheus65535** [comment]
It's not a maturity issue, you haven't installed py3-psycopg2 package using your operating system package manager. You can check how hotio do it in his image: https://github.com/hotio/bazarr/blob/nightly/linux-amd64.Dockerfile

**Comment by onedr0p** [comment]
Ugh yeah my bad, I fat-fingered removing the 2 on the end of `py3-psycopg2`

**Comment by onedr0p** [comment]
3.10 is good 👍🏼 Sorry for the confusion.

**Comment by morpheus65535** [comment]
No problem. Don't hesitate to report further issues. There's not much postgres users so bug wont fix themselves ;-)
