### ISSUE TITLE
Erratic subtitle download behavior.

### ISSUE THREAD

**Issue by ryanjoachim** [morpheus65535/bazarr#225]
****Describe the bug**
A clear and concise description of what the bug is.**
I've been struggling to download subtitles lately (on Windows 10), with over 4000 wanted but only 10 downloaded in the last week.

This error I just received (in screenshots below) when manually running the "download wanted subtitles" option. The highlighted error is one I've seen frequently in the last week or so during the scheduled search task.

**To Reproduce**
Have Opensubtitles enabled.
Have scheduled download task run, or manually run per-show, or manually start the library-wide download search.
Be on Windows 10.

**Expected behavior**
Subtitles to download (respective of API limits) with no errors, or errors related to subtitles not existing.

**Screenshots**
https://media.discordapp.net/attachments/382221826564030470/511813332110671872/unknown.png
https://media.discordapp.net/attachments/382221826564030470/511868147184435201/unknown.png?width=496&height=683
https://media.discordapp.net/attachments/382221826564030470/511870457280987138/unknown.png?width=760&height=684

**Software (please complete the following information):**
 - Bazarr: v0.6.7.1
 - Radarr version 0.2.0.1120
 - Sonarr version 2.0.0.5252
 - OS: Windows 10

**Additional context**
All episodes are set to English as the only language. I previously only had opensubtitles active, but I've since added Addic7ed and thesubdb with the same results.

**Comment by morpheus65535** [comment]
I cannot reproduce. Could you provide an episode filename in problem so I can try to reproduce it outside of bazarr?

**Comment by ryanjoachim** [comment]
Sorry - I cannot find any episode specified as the cause of the issue.
I have attached a screenshot of the last several subtitles download over the last few days.

![image](https://user-images.githubusercontent.com/20692061/48700060-e63ec180-eb9f-11e8-8401-0a5552f2b97a.png)
One thing I noticed is that it sometimes seems like the same episode is downloading freaquently.

**Comment by morpheus65535** [comment]
Is your media storage local or somewhere on the internet? I don’t see why the same subtitles is downloaded many time... looks like it’s not indexed properly after download.

**Comment by ryanjoachim** [comment]
Sorry - I cannot find any episode specified as the cause of the issue. I have over 4000 subtitles wanted, so I'm not sure how to find a specific one causing this issue.
I have attached a screenshot of the last several subtitles download over the last few days.

![image](https://user-images.githubusercontent.com/20692061/48700060-e63ec180-eb9f-11e8-8401-0a5552f2b97a.png)
One thing I noticed is that it sometimes seems like the same episode is downloading frequently.

**Comment by ryanjoachim** [comment]
[bazarr.log](https://github.com/morpheus65535/bazarr/files/2612677/bazarr.log)
[bazarr-non_debug.log](https://github.com/morpheus65535/bazarr/files/2612678/bazarr-non_debug.log)

Apologies for the long wait. I have attached two logs - one with debugging turned on, and one without. 
I manually ran the subtitle search task after clearing the logs for each file, and let it run for around an hour.

**Comment by ryanjoachim** [comment]
Here is another log - just one error message after being on for a few minutes so far.

[bazarr.log](https://github.com/morpheus65535/bazarr/files/2613040/bazarr.log)

**Comment by morpheus65535** [comment]
Disable adaptive search for a while to get missing subtitles. This log item means that search is postponed for this item because after a month of searching, there wasn't any result: `BAZARR Search is not active for episode...`.

Regarding the `LangDetectException: No features in text.` exception, I'm going to add some code to catch this exception.

Please report ni a week with your progress. Thanks!

**Comment by morpheus65535** [comment]
Should be fixed in the next release (0.6.9).

**Comment by ryanjoachim** [comment]
I know you marked this as closed, but I wanted to post the results after a week (as initially requested).
I disabled adaptive search as you suggested.

![image](https://user-images.githubusercontent.com/20692061/49431978-80d3fe80-f763-11e8-8c58-dd4b7d194afe.png)
[bazarr.log](https://github.com/morpheus65535/bazarr/files/2643179/bazarr.log)

I am still seeing subtitles being downloaded over and over again. I have deleted all previously-existing subtitle files prior to this log being made.

**Comment by morpheus65535** [comment]
Please provide the following:
- screenshot of your main series page
- screenshot of the `path mapping for series` section of general settings
- screenshot of the path of a series for Sonarr
- screenshot of the path of the same series in Bazarr

Thanks!

**Comment by ryanjoachim** [comment]
![image](https://user-images.githubusercontent.com/20692061/49466263-74c45d00-f7b4-11e8-9403-2e278f686643.png)
![image](https://user-images.githubusercontent.com/20692061/49466319-9c1b2a00-f7b4-11e8-89bf-80fe4707fb22.png)
![image](https://user-images.githubusercontent.com/20692061/49466423-e13f5c00-f7b4-11e8-8c4a-675e3ee85e3c.png)
![image](https://user-images.githubusercontent.com/20692061/49466465-016f1b00-f7b5-11e8-834e-4aa0e8b3cf20.png)

**Comment by morpheus65535** [comment]
Everything seems to be ok from what I can see.

I'm adding a lot of debug logging to the existing subtitles indexing and will release 0.6.9 that will include this debug logging. Please provide a debug log of a "scan subtitles from disk" operation (dual arrows) if you still have the problem with 0.6.9. You should be able to update to 0.6.9 in the next hours.

**Comment by ryanjoachim** [comment]
The log file gets pretty massive after a while (turned on debug logging for around 20 minutes today and the file was already up to 40MB), so it's too large to upload here.

What would be a good alternative upload spot for you to access?

**Comment by morpheus65535** [comment]
Discord?
