### ISSUE TITLE
assrt get throttled due to http error code 493

### ISSUE THREAD

**Issue by tankren** [morpheus65535/bazarr#802]
**Describe the bug**
assrt get throttled due to http error code 493
Throttling assrt for 30 seconds, until 20/02/05 13:29, because of: HTTPError. Exception info: '493 Client Error:  for url: http://assrt.net/download/error/xxxxxxx'

**To Reproduce**
_**Please refer to Additional context**_

**Expected behavior**

**Screenshots**

**Software (please complete the following information):**
 - Bazarr: [v0.8.4.1]
 - Radarr version [v0.2.0.1450]
 - Sonarr version [v3.0.3.690]
 - OS: [OMV5, based on debian 10 buster]

**Additional context**
  The root cause should be provider issue, API works great but error happened when downloading the file. I can simulate and reproduce similar case on the providers website, e.g: http://assrt.net/xml/sub/610/610415.xml
  If I download specific sub by click the link in the list, http://assrt.net/download/error/xxxxxx will show but the archived zip file can be downloaded
  Wonder if @dimotsai would help to update the code to download the zip file and fetch the wanted sub file in it to bypass the provider server issue. thanks.

PS: I changed the time delta to 30 sec instead of 10 min in assrt.py when hit error to save the time.
 
attached the log file:
[bazarr.log](https://github.com/morpheus65535/bazarr/files/4157679/bazarr.log)

**Comment by morpheus65535** [comment]
@dimotsai could you take a look please?

**Comment by dimotsai** [comment]
Sorry for the late response

It seems to be a server issue instead of the provider. The API provides
separated download links for each file of the archive. But the API seems
broken somehow.

@tankren Would you please try other subtitles, see if the problem stands
for all cases.

I would take a look if I am free :)

morpheus65535 <notifications@github.com> 於 2020年2月18日 週二 01:43 寫道：

**Comment by dimotsai** [comment]
I've written to the website administrator, see if he/she can provide us
hints

蔡志豪 <dimotsai.tw@gmail.com> 於 2020年2月18日 週二 11:35 寫道：

**Comment by dimotsai** [comment]
I just got replied that there were some sort of zip encoding issues and it
has been fixed now.

@tankren Please try again, see if it works properly.

**Comment by tankren** [comment]
> I just got replied that there were some sort of zip encoding issues and it has been fixed now. @tankren Please try again, see if it works properly.

hi there, pls give a few guidance on how to test, I did not find the commit targeting my issue, thanks.

**Comment by morpheus65535** [comment]
@tankren my understanding is that the fix happen on assrt side. You can just test with your actual version of Bazarr.

**Comment by tankren** [comment]
> @tankren my understanding is that the fix happen on assrt side. You can just test with your actual version of Bazarr.

Thank you both, deleted all the srt subtitles of GoT and started a manual search, no more 493 errors.

However I found another "issue" regarding the score match. the total number of GoT subtitles is 78, after manual search, 43 of 78 are still missing. according to the debug log, I realized that it's due to that score was below min score. For example as S01E01, the best score is 303 but it's below min score 324, dunno how these values were calculated, I checked the score setting in Subtitle tab, the config is as below:
`Minimum Score For Episodes  90`
`Minimum Score For Movie 70`
is this normal? thanks
[bazarr.log](https://github.com/morpheus65535/bazarr/files/4236270/bazarr.log)

**Comment by morpheus65535** [comment]
Good news that your issue is fixed!

For th scoring, that's a normal behavior. You can see how score are calculated here: https://github.com/morpheus65535/bazarr/blob/development/libs/subliminal/score.py#L39-L45

Basically, in the UI it's a percentage of score over maximum score (360 for episode and 120 for movie).
